### ISSUE TITLE
Amazing project, but might be possible to do 32 bit?

### ISSUE THREAD

**Issue by kblood** [Baron-von-Riedesel/Dos64-stub#3]
The HX DOS Extender tried do something similar to this, but with 32 bit instead.
https://www.japheth.de/HX.html

Not having to rely on a x64 would be pretty awesome. The HX DOS Extender does seem to be dead and not sure there is any source code for it, but figured maybe it could be some inspiration.

**Comment by lpsantil** [comment]
https://github.com/Baron-von-Riedesel/HX

https://github.com/Baron-von-Riedesel/HimemSX

**Comment by Baron-von-Riedesel** [comment]
FYI, I am the author of HX. 

The closest match to dos64stb.bin in 32-bit would be the stub loadpe.bin in HX.

**Comment by kblood** [comment]
Awesome, that is very nice to know. Thanks. Good work on HX btw.

**Comment by kblood** [comment]
I really should have looked for HX source code first. I think I mixed it up with something else I had been looking into. Sorry about that. Especially since I was already on the git that has the source.

I can see it even has very recent updates, happy to see that. Looking forward to play around with this on my MiSTer FPGA using the AO486 core. It does runs a rather good x86 core.
